### PR TITLE
Add Django 2.2 Support In Travis

### PR DESCRIPTION
**Pull request by bhonshell**

### CODE REVIEW

**Comment by bashu** [comment]
hey @bhonshell please fix it and reopen PR

**Comment by npardington** [comment]
How would you like this fixed? We could either support only the most recent version of Wagtail (it looks like they dropped support for Django 1.11.x https://github.com/wagtail/wagtail/tree/v2.4#compatibility) with each release. Or something different @bashu?

**Comment by paperreduction** [comment]
@bashu Just to clarify this so we're all on the same page:

We would like to add support for wagtail 2.5. We updated your project but we now have a failing test, I believe due to django 1.11 support.

Wagtail dropped Django 1.11 support AFTER 2.3 (2.3 was the last django 1.11 version). From the release notes: 

> Note that Wagtail 2.3 will be the last release branch to support Django 1.11.

http://docs.wagtail.io/en/v2.5.1/releases/2.3.html

So we would like to also drop the django 1.11 requirement from your project along with the wagtail version bump to wagtail 2.5. This should fix the failing test.

@npardington Was trying to make sure that was going to be a good solution for you. We'll reopen the pull request with those changes if that works for you. Thanks!

**Comment by bashu** [comment]
@paperreduction just do it! (c) Shia LaBeouf

**Pull request closed without merging**
