### PR TITLE
simple update v2.0

### PR DESCRIPTION
**Pull request by bashu**

### CODE REVIEW

**Comment by kbrownlees** [comment]
What is the status of this? Looks like the tests are failing in 2.7 - could just drop 2.7 support from this release?

This is blocking any upgrades to wagtail 2.x.

**Comment by bashu** [comment]
@recklessromeo thanks

**Comment by bashu** [comment]
@dadafari and thank you too =)

**Comment by bashu** [comment]
@recklessromeo @kbrownlees stay tuned for upcoming release

**Pull request merged**
